package doro.page;

/**
 * Created by Caibing.yin on 2017/1/12.
 */

public class MenuPage {
    public static String AppNameList[] = {
            "Alarm",
            "Calcular", "Camera", "Chrome", "Code Safe", "Contacts",
            "Dock mode", "Doro Connect & Care", "Doro Keyboard ", "Doro Selection", "Downloads", "Drive", "Duo",
            "Email", "Email",
            "File Manager", "FM Radio",
            "Gallery", "Gmail", "Google",
            "Internet",
            "Magnifier", "Maps", "Messages", "Music", "My Doro Manager",
            "Notes",
            "Phone", "Photos", "Play Movies & TV", "Play Music", "Play Store",
            "QuickSupport",
            "Recorder",
            "Settings", "SIM Tool Kit",
            "Timer", "Torch",
            "Voice Search",
            "Weather",
            "YouTube",
    };
    public static String PkgNameList[]={
            "com.doro.apps.alarm",
            "com.doro.apps.calculator",
            "com.mediatek.camera",
            "com.doro.apps.calendar",
            "com.android.chrome",
            "",
            "com.doro.apps.contacts",
            "com.doro.apps.dock",
            "com.doro.cnc.mobile",
            "com.doro.inputmethod.latin",
            "com.doro.apps.doroselection",
            "com.android.documentsui",
            "com.google.android.gms",
            "com.google.android.apps.tachyon",
            "com.doro.apps.email",
            "com.doro.apps.email",
            "com.mediatek.filemanager",
            "com.android.fmradio",
            "com.doro.apps.gallery",
            "com.google.android.gm",
            "com.google.android.googlequicksearchbox",
            "com.doro.apps.internet",
            "com.doro.apps.magnifier",
            "com.google.android.apps.maps",
            "com.doro.apps.messages",
            "com.doro.apps.musicplayer",
            "com.doro.cnc.mobile",
            "com.doro.apps.notes",
            "com.doro.apps.phone",
            "com.google.android.apps.photos",
            "com.mediatek.camera",
            "com.google.android.music",
            "com.google.android.gms",
            "com.google.android.play store",
            "com.teamviewer.quicksupport.market",
            "com.doro.apps.soundrec",
            "com.doro.settings",
            "SIM Tool Kit",
            "com.doro.apps.timer",
            "com.doro.apps.torch",
            "com.google.android.googlequicksearchbox",
            "com.doro.apps.weather",
            "com.google.android.youtube",
            "",
            "",
            "",
    };
    public static final String More = "com.doro.apps.launcher3:id/more_actions";
}
